name: Publish to NuGet
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
      - name: Build
        run: dotnet build -c Release
      - name: Pack NuGet packages
        run: dotnet pack -c Release --no-build --output .
      - name: Publish to NuGet
        run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.GIT_PACKAGES_TOKEN }} --source "github"
1